// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MediaLibrary.DAL.Models;

[Table("Genre")]
public partial class Genre
{
    [Key]
    public int Id { get; set; }

    [Required]
    [StringLength(150)]
    [Unicode(false)]
    public string Name { get; set; }

    public DateTime CreateDate { get; set; }

    public DateTime ModifyDate { get; set; }

    [InverseProperty("Genre")]
    public virtual ICollection<Album> Albums { get; set; } = new List<Album>();

    [InverseProperty("Genre")]
    public virtual ICollection<Track> Tracks { get; set; } = new List<Track>();
}