// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MediaLibrary.DAL.Models;

[Table("Playlist")]
public partial class Playlist
{
    [Key]
    public int Id { get; set; }

    [Required]
    [StringLength(150)]
    [Unicode(false)]
    public string Name { get; set; }

    public DateTime CreateDate { get; set; }

    public DateTime ModifyDate { get; set; }

    [InverseProperty("Playlist")]
    public virtual ICollection<PlaylistEpisode> PlaylistEpisodes { get; set; } = new List<PlaylistEpisode>();

    [InverseProperty("Playlist")]
    public virtual ICollection<PlaylistPodcastItem> PlaylistPodcastItems { get; set; } = new List<PlaylistPodcastItem>();

    [InverseProperty("Playlist")]
    public virtual ICollection<PlaylistTrack> PlaylistTracks { get; set; } = new List<PlaylistTrack>();
}