// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MediaLibrary.DAL.Models;

public partial class Series
{
    [Key]
    public int Id { get; set; }

    [Required]
    [StringLength(256)]
    [Unicode(false)]
    public string Title { get; set; }

    public DateTime CreateDate { get; set; }

    public DateTime ModifyDate { get; set; }

    [InverseProperty("Series")]
    public virtual ICollection<Episode> Episodes { get; set; } = new List<Episode>();
}