// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MediaLibrary.DAL.Models;

[Table("TrackPath")]
public partial class TrackPath
{
    [Key]
    public int Id { get; set; }

    [Required]
    [Unicode(false)]
    public string Location { get; set; }

    public DateTime LastScanDate { get; set; }

    public DateTime CreateDate { get; set; }

    public DateTime ModifyDate { get; set; }

    [InverseProperty("Path")]
    public virtual ICollection<Track> Tracks { get; set; } = new List<Track>();
}